# Generated by Django 3.2.13 on 2022-07-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_posts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
