# Generated by Django 4.0.6 on 2022-07-17 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0004_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
