# Generated by Django 3.2.13 on 2022-06-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_specialities_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialities',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='specialities',
            name='special',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
