# Generated by Django 3.2.13 on 2022-06-28 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date_time_start', models.DateTimeField(blank=True, null=True)),
                ('date_time_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('finished', 'finished'), ('upcoming', 'upcoming'), ('ongoing', 'ongoing')], max_length=20, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
