# Generated by Django 4.0.6 on 2022-10-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date_time_end',
        ),
    ]
