# Generated by Django 3.2.13 on 2022-07-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctors_profile_image'),
        ('patients', '0002_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_doctor', to='doctors.doctors'),
        ),
    ]
