# Generated by Django 3.2.13 on 2022-06-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_familymembers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembers',
            name='relation',
            field=models.CharField(max_length=50),
        ),
    ]
