# Generated by Django 3.2.13 on 2022-06-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='slug',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialized_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.specialities'),
        ),
    ]
