# Generated by Django 3.2.13 on 2022-06-27 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0002_auto_20220627_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='charge',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL),
        ),
    ]
