# Generated by Django 3.2.13 on 2022-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20220627_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='charge',
            field=models.PositiveIntegerField(),
        ),
    ]
