# Generated by Django 3.2.13 on 2022-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctors_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='images/doctors'),
        ),
    ]
