# Generated by Django 4.0.6 on 2022-07-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctors_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='paypal_account',
            field=models.EmailField(max_length=70, null=True),
        ),
    ]
