# Generated by Django 4.0.6 on 2022-08-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctors_paypal_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='paypal_account',
            field=models.EmailField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
